### ISSUE TITLE
Variable envelope return path (VERP) for CiviMail

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/mailserver#1]
CiviMail has the option to [use VERP for bounce handling](https://docs.civicrm.org/sysadmin/en/latest/setup/civimail/inbound/). This requires a mail server that can handle [VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path) return addresses. Will the new mail server support VERP?

**Comment by wunluv** [comment]
It certainly will. Our MTA has [VERP.](http://www.postfix.org/VERP_README.html) The recipe I know fairly well is Postfix + Dovecot + spamassasin + roundcube. I take a shortcut by using the very same BOA script that we use to build our Nginx/Mariadb server - which has given me a low maintenance mail server for many years. I think the process of documenting the build, like we discussed, would lower the maintenance input further.

Yes, we can do VERP.

**Comment by rgilman** [comment]
Great! I'll close this issue now.
